# Permalinks
permalink:           pretty

# Setup
title:               Christina Wayman, PhD
tagline:             A Data Science Blog
url:                 http://drchristina.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Christina Wayman
  url:               https://www.wayman.xyz
  email:            christina@wayman.xyz

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/drchristina

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
